Remove protein_db column
EBI-Metagenomics/emg-backlog-schema pull request #34
Opened 2021-07-29 15:10 UTC by KeteSakharova

there is no need to have this column anymore

2021-07-30 08:00 UTC, mberacochea requested changes

2021-07-30 08:00 UTC, mberacochea commented on backlog/migrations/0076_auto_20210729_1509.py
> +        migrations.AlterField(
This migration statement is not present in the changes you made to the models. Maybe you forgot to commit a file?

2021-08-12 13:05 UTC, mberacochea approved these changes

2021-08-13 16:20 UTC, KeteSakharova commented
Lets test on dev

2021-08-13 16:20 UTC, merged